import { z } from 'zod';

// Employee code (کد پرسنلی) is NOT part of this schema — it is generated by
// EmployeesService.create() from the department's code plus the new
// employee's id, and is never supplied by the client.

// First/last name (and father's name, which follows the same rule): Persian
// letters, spaces, and the "نیم‌فاصله" (ZWNJ) only — no Latin letters, no
// digits (Latin or Persian), no symbols.
const PERSIAN_NAME_REGEX = /^[آابپتثجچحخدذرزژسشصضطظعغفقکگلمنوهیئؤأإء‌ ]+$/;

const EDUCATION_LEVELS = ['under_diploma', 'diploma', 'associate', 'bachelor', 'master', 'phd'] as const;
const MARITAL_STATUSES = ['single', 'married'] as const;
const GENDERS = ['male', 'female'] as const;
const CONTRACT_TYPES = ['permanent', 'temporary', 'fixed_task'] as const;
const SALARY_PERIODS = ['monthly', 'weekly', 'daily'] as const;

// Shared helper: an empty string from the form means "not provided" for
// every optional field below, not a value to validate.
function emptyToUndefined(value: unknown) {
  return typeof value === 'string' && value.trim() === '' ? undefined : value;
}

function optionalTrimmedString(maxLength: number) {
  return z.preprocess(emptyToUndefined, z.string().trim().max(maxLength).optional());
}

function optionalPersianName(label: string, maxLength = 80) {
  return z.preprocess(
    emptyToUndefined,
    z.string().trim().max(maxLength).regex(PERSIAN_NAME_REGEX, `${label} باید فقط شامل حروف فارسی باشد`).optional(),
  );
}

function optionalEnum<T extends readonly [string, ...string[]]>(values: T) {
  return z.preprocess(emptyToUndefined, z.enum(values).optional());
}

function optionalNonNegativeInt(message: string) {
  return z.preprocess(emptyToUndefined, z.coerce.number().int().min(0, message).optional());
}

function optionalNonNegativeDecimal(message: string) {
  return z.preprocess(emptyToUndefined, z.coerce.number().min(0, message).optional());
}

function optionalDate() {
  return z.preprocess(emptyToUndefined, z.coerce.date().optional());
}

// Mobile phone (تلفن همراه): required, exactly 11 Latin digits — same
// format rule already used for User accounts.
const mobilePhone = z
  .string()
  .trim()
  .regex(/^[0-9]{11}$/, 'تلفن همراه باید دقیقاً ۱۱ رقم انگلیسی باشد');

// Landline phone (تلفن ثابت): optional, digits only.
const optionalLandlinePhone = z.preprocess(
  emptyToUndefined,
  z.string().trim().regex(/^[0-9]{6,11}$/, 'تلفن ثابت معتبر نیست').optional(),
);

const optionalEmail = z.preprocess(
  emptyToUndefined,
  z.string().trim().email('ایمیل معتبر نیست').optional(),
);

const employeeFields = {
  firstName: z
    .string()
    .trim()
    .min(1, 'نام الزامی است')
    .max(80)
    .regex(PERSIAN_NAME_REGEX, 'نام باید فقط شامل حروف فارسی باشد'),
  lastName: z
    .string()
    .trim()
    .min(1, 'نام خانوادگی الزامی است')
    .max(80)
    .regex(PERSIAN_NAME_REGEX, 'نام خانوادگی باید فقط شامل حروف فارسی باشد'),
  departmentId: z.number().int().positive('واحد سازمانی را انتخاب کنید'),
  position: z.string().trim().max(120).optional(),
  // National ID (کد ملی) and birth date are required — the company asked
  // for both to be mandatory going forward.
  nationalId: z
    .string()
    .trim()
    .min(1, 'کد ملی الزامی است')
    .regex(/^[0-9]{10}$/, 'کد ملی باید دقیقاً ۱۰ رقم انگلیسی باشد'),
  mobilePhone,
  landlinePhone: optionalLandlinePhone,
  birthDate: z.coerce.date(),
  hireDate: z.coerce.date(),
  email: optionalEmail,
  note: optionalTrimmedString(1000),

  // --- اطلاعات هویتی و خانوادگی (identity & family, all optional) ---
  fatherName: optionalPersianName('نام پدر'),
  birthCertificateNumber: optionalTrimmedString(20),
  maritalStatus: optionalEnum(MARITAL_STATUSES),
  childrenCount: optionalNonNegativeInt('تعداد فرزندان باید عددی صحیح و غیرمنفی باشد'),
  gender: optionalEnum(GENDERS),

  // --- تحصیلات (education) ---
  educationLevel: optionalEnum(EDUCATION_LEVELS),
  // Only meaningful when educationLevel is "under_diploma" — enforced
  // together with educationLevel below, not as an independent field rule.
  belowDiplomaGrade: optionalTrimmedString(50),
  fieldOfStudy: optionalTrimmedString(100),

  // --- اطلاعات استخدام و قرارداد (employment & contract) ---
  workLocation: optionalTrimmedString(200),
  workingHours: optionalTrimmedString(100),
  contractType: optionalEnum(CONTRACT_TYPES),
  contractStartDate: optionalDate(),
  contractEndDate: optionalDate(),
  // Paired with salaryPeriod below — enforced together, not independently.
  salaryAmount: optionalNonNegativeDecimal('مبلغ حقوق باید عددی غیرمنفی باشد'),
  salaryPeriod: optionalEnum(SALARY_PERIODS),
  // Free text — plain account number, card number, or Sheba/IBAN.
  bankAccountNumber: optionalTrimmedString(34),

  // --- اطلاعات تماس و سایر (contact & other) ---
  address: optionalTrimmedString(500),
};

// Cross-field rules that can't be expressed on a single field in isolation.
// Applied to both create and update so the same rules hold either way.
function withCrossFieldRules<T extends z.ZodTypeAny>(schema: T) {
  return schema.superRefine((data, ctx) => {
    const record = data as Record<string, unknown>;
    if (record.educationLevel === 'under_diploma' && !record.belowDiplomaGrade) {
      ctx.addIssue({
        code: 'custom',
        path: ['belowDiplomaGrade'],
        message: 'در صورت انتخاب «زیر دیپلم»، مقطع تحصیلی (تا چه کلاسی) را مشخص کنید',
      });
    }
    const start = record.contractStartDate as Date | undefined;
    const end = record.contractEndDate as Date | undefined;
    if (start && end && end.getTime() < start.getTime()) {
      ctx.addIssue({
        code: 'custom',
        path: ['contractEndDate'],
        message: 'تاریخ پایان قرارداد نمی‌تواند قبل از تاریخ شروع باشد',
      });
    }
    // "حقوق" is really one field (amount + period) split into two columns —
    // an amount without knowing ماهانه/هفتگی/روزانه isn't meaningful data.
    if (record.salaryAmount !== undefined && !record.salaryPeriod) {
      ctx.addIssue({
        code: 'custom',
        path: ['salaryPeriod'],
        message: 'دوره پرداخت حقوق (ماهانه، هفتگی یا روزانه) را مشخص کنید',
      });
    }
  });
}

export const createEmployeeSchema = withCrossFieldRules(z.object(employeeFields));
export const updateEmployeeSchema = withCrossFieldRules(
  z.object(employeeFields).extend({ status: z.enum(['active', 'on_leave', 'terminated']) }),
);
export type CreateEmployeeDto = z.infer<typeof createEmployeeSchema>;
export type UpdateEmployeeDto = z.infer<typeof updateEmployeeSchema>;
